version: "3"
services:
  etl-db:
    image: postgres:11
    container_name: etl-db
    restart: always
    networks:
      - etl-network
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=etl-db
    ports:
      - 5432:5432

networks:
  etl-network:
    driver: bridge